Id: Corel.WinZip
Version: 24.0.14033
Name: WinZip
Publisher: Corel
License: Copyright (c) Corel Corporation.
LicenseUrl: https://www.winzip.com/win/en/eula.html
AppMoniker: WinZip
Tags: rar zip winzip compression
Description: WinZip Compression Utility
Homepage: https://www.winzip.com
Installers:
  - Arch: x86
    Url: https://download.winzip.com/winzip240-32.msi
    Sha256: ABD8955C4082D608EC4AD46348ABE545C1536B16A88422D77DA9A4136EB404E5
    InstallerType: msi
  - Arch: x64
    Url: https://download.winzip.com/winzip240-32.msi
    Sha256: 7D802DCED0C52A775D2C20B332BF9157339C21AC5FBABCB29FA6409745910DDB
    InstallerType: msi
