Id: Corel.WinZip
Version: 25.0.14273
ManifestVersion: 1.25.0
Name: WinZip
Publisher: Corel
License: Copyright (c) Corel Corporation. All Rights Reserved.
LicenseUrl: https://www.winzip.com/win/en/eula.html
AppMoniker: WinZip
Tags: rar zip winzip compression
Description: WinZip Compression Utility
Homepage: https://www.winzip.com
Installers:
  - Arch: x64
    Url: https://download.winzip.com/winzip250-64.msi
    Sha256: 7E7EA57A4DF209595EDC36A161A4BCDFE86B216CAE30355896ED9C902A9E5EC8
    InstallerType: msi
